export const locations = [
  { id: "1", name: "Chennai", state: "TN" },
  { id: "2", name: "Coimbatore", state: "TN" },
  { id: "3", name: "Madurai", state: "TN" },
  { id: "4", name: "Salem", state: "TN" },
  { id: "5", name: "Tirchy", state: "TN" },
  { id: "6", name: "Tirunelveli", state: "TN" },
  { id: "7", name: "Vellore", state: "TN" },
  { id: "8", name: "Thanjavur", state: "TN" },
  { id: "9", name: "Erode", state: "TN" },
  { id: "10", name: "Tiruppur", state: "TN" },
];

export const topRoutes = [
  {
    id: "1",
    from: "Chennai",
    to: "Madurai",
    departureTime: "10:00",
    arrivalTime: "20:00",
    duration: "10 Hrs",
    price: 1600,
    busNumber: "TN01",
    seatsAvailable: 45,
    amenities: ["internet", "snacks", "tv", "charging"],
  },
  {
    id: "2",
    from: "Coimbatore",
    to: "Chennai",
    departureTime: "08:00",
    arrivalTime: "16:00",
    duration: "8 Hrs",
    price: 1300,
    busNumber: "TN02",
    seatsAvailable: 38,
    amenities: ["internet", "snacks", "tv", "charging"],
  },
  {
    id: "3",
    from: "Madurai",
    to: "Tirunelveli",
    departureTime: "09:00",
    arrivalTime: "21:00",
    duration: "12 Hrs",
    price: 2200,
    busNumber: "TN03",
    seatsAvailable: 42,
    amenities: ["internet", "snacks", "tv", "charging"],
  },
  {
    id: "4",
    from: "Salem",
    to: "Chennai",
    departureTime: "07:00",
    arrivalTime: "13:00",
    duration: "6 Hrs",
    price: 1000,
    busNumber: "TN04",
    seatsAvailable: 40,
    amenities: ["internet", "snacks", "tv", "charging"],
  },
  {
    id: "5",
    from: "Tiruchy",
    to: "Coimbatore",
    departureTime: "14:00",
    arrivalTime: "06:00",
    duration: "16 Hrs",
    price: 2000,
    busNumber: "TN05",
    seatsAvailable: 35,
    amenities: ["internet", "snacks", "tv", "charging"],
  },
  {
    id: "6",
    from: "Vellore",
    to: "Salem",
    departureTime: "09:00",
    arrivalTime: "17:00",
    duration: "8 Hrs",
    price: 1400,
    busNumber: "TN06",
    seatsAvailable: 44,
    amenities: ["internet", "snacks", "tv", "charging"],
  },
];
